### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by proxyswitch** [mpyw/cowitter#11]
$status = $client->post('statuses/update', array('status' => 'Proxy Tweet.'),'https://111.222.333.444:8080');

Proxy Not Supporting .. :(

**Comment by mpyw** [comment]
I'm sorry, but there are no TwistOAuth-style configurations anymore. In Cowitter, it is done with

```php
$client = new ([...], [CURLOPT_PROXY => 'https://111.222.333.444:8080']);
```

or

```php
$client = new ([...]);
$client = $client->withOptions([CURLOPT_PROXY => 'https://111.222.333.444:8080']);
```
