### ISSUE TITLE
Example exception 'oob'

### ISSUE THREAD

**Issue by sinbadxiii** [mpyw/cowitter#12]
Please,  can you give an example code, when an exception is thrown 'oob' and it is necessary to enter your email or phone?

**Comment by mpyw** [comment]
Did you mean the exception that says `Desktop applications only support the oauth_callback value 'oob'`? It has nothing to do with requiring email or phone number.

- [TwitterのOAuthでCallbackさせるときの注意点 - speg03の雑記帳](http://d.hatena.ne.jp/speg03/20091019/1255957580)<br>(Written in Japanese, so you should read via Google Translate.)

This article says:

> When you need to authorize on Web applications,
> - Set `Application Type` to Browser.
> - Fill `Callback URL` anyway. **(Even if you're going to specify in your PHP scripts)**
